### ISSUE TITLE
Server crash on load- java.lang.NoClassDefFoundError: me/flibio/updatifier/UpdatifierServiceImpl

### ISSUE THREAD

**Issue by ProsperCraft** [FlibioStudio/Updatifier#10]
http://pastebin.com/mxnvW6sQ

**Comment by liach** [comment]
Ah one of your sponge plugins are shipping an outdated updatifier api, i assume. i will figureit out later. You can remove updatifier to make the server run.

**Comment by liach** [comment]
@hsyyid Could you update your updatifier api version to 1.4.0? As I see this bug is caused by outdated api in essentialcmds.

**Comment by ProsperCraft** [comment]
updated essentialscmds to  EssentialCmds-7.8e.jar still using old api.

http://pastebin.com/fk5nYx9p

**Comment by hsyyid** [comment]
@liach Will do so.

**Comment by liach** [comment]
@prospercraft Wait for the next release of essentialcmds.
