### ISSUE TITLE
A new way of checking updates

### ISSUE THREAD

**Issue by kinggoesgaming** [FlibioStudio/Updatifier#11]
Currently we have the `@Updatifier` annotation and the `UpdatifierService`. I understand this was made before @windy1 introduced the Asset API. I have been messing with the Asset API and have managed to think of a way that will allow plugin devs not even depend on Updatifier and still manage to have the integration. So here it goes: (**Warning**: Big wall of text)

---

Every plugin can have a file in the `assets/<pluginId>/` called `updatifier.conf` which can have contents similar to this:

``` hocon
############################
# Support for Ore
############################
# Basically a true or false. Since all
# plugins have a unique id on ore,
# this will allow just that one line
# and plugins can get updates.
############################
ore : true
############################
# Support for GitHub
############################
# Same as the annotation/ service
############################
github : {
    repoOwner: <user/org>
    repoName: <repo>
    version: <version>
}
```

---

**Use Cases**
- Allows developers to have support for Updatifier without having to depend on it.
- Makes the plugin more extendable as more services like maven, bitbucket can be added.
- Other usecases that I can't think of right now :confused: 

---

This can allow for the Updatifier API to be removed(maybe deprecate first :yum:) 

---

I would love discussion on this.

Edit by @liach:
Fixed a wrong poke...

**Comment by Flibio** [comment]
This looks like a really interesting idea! Thanks for suggesting it, I will definently think about implementing it.

Pinging @liach to take a look at this.

**Comment by kinggoesgaming** [comment]
So I thought about how to make the github section more refined github section.

```hocon
github : {
    owner : <repo_owner>
    name : <repo_name>
    meta : {
      version : <current_version>
      prefix : "v"
      suffix : "suffix"
    }
}
```
the meta data is optional. `prefix` and `suffix` are completely used to format the url string. If `version` is given, then then that version is used else plugin's version from plugincontainer is used.

**Comment by kinggoesgaming** [comment]
@Flibio I want to start working on this... Any changes you want in here?

**Comment by Flibio** [comment]
Nothing specific, just what you described above.

**Comment by kinggoesgaming** [comment]
I am switching from HOCON to JSON.

**Comment by kinggoesgaming** [comment]
closing as ore will now supersede this
