### ISSUE TITLE
Use guice instead of static reference

### ISSUE THREAD

**Issue by kinggoesgaming** [FlibioStudio/Updatifier#12]
Reference: https://github.com/FlibioStudio/Updatifier/blob/master/src/main/java/me/flibio/updatifier/UpdatifierPlugin.java#L65

**Comment by kinggoesgaming** [comment]
Just for record, I will be PRing this

**Comment by Flibio** [comment]
Closed with f05217b47e5a283e5d461858c7a5fed5c73de1d7.
