### ISSUE TITLE
Fix project structure

### ISSUE THREAD

**Issue by kinggoesgaming** [FlibioStudio/Updatifier#13]
this picture shows it off clearly

![image](https://cloud.githubusercontent.com/assets/15664607/15631068/8f42faa4-2509-11e6-9744-7046e9a7351c.png)

the me.flibio... packages should go into the java module, the api module inside of the main should not exist. I will be PRing soon to fix this

**Comment by Flibio** [comment]
The API package is separated so that plugins do not have to include all of Updatifier when they want to add it as a dependency. The API package should be kept separated.

**Comment by kinggoesgaming** [comment]
I meant the API package inside main module

**Comment by Flibio** [comment]
Ah, I see how you changed it.
