### ISSUE TITLE
More Supports

### ISSUE THREAD

**Issue by liach** [FlibioStudio/Updatifier#2]
- [ ] Support for [Ore](https://ore-staging.spongepowered.org/)
  - ~~See SpongePowered/Ore#5 for reference~~
  - See https://github.com/SpongePowered/Ore/blob/master/conf/routes#L14-L31
- [ ] Support for checking against Maven builds
  - Reference: https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.3.9/ might be a useful library

**Comment by Flibio** [comment]
I'm planning on doing this when Ore is complete.

**Comment by kinggoesgaming** [comment]
cleaning out ~~my closet~~ issues list
