### ISSUE TITLE
Use Gradle Shadow instead of custom shading

### ISSUE THREAD

**Issue by Flibio** [FlibioStudio/Updatifier#27]
Reference: https://github.com/johnrengelman/shadow

**Comment by kinggoesgaming** [comment]
I like this, however, we need to be vary as sometimes other Gradle plugins tend to interfere, from experience I know.

**Comment by liach** [comment]
d5f38b824e2c6bdd1885a2374116869258e5bd8f

**Comment by kinggoesgaming** [comment]
Woops

**Comment by kinggoesgaming** [comment]
cleaning out ~~my closet~~ issues list
